all:
  vars:
    ansible_user: root
  children:
    mail_servers:
      hosts:
        mail.massopen.cloud:
    freeipa_managed:
      children:
        auth_servers:
          hosts:
            sso1.massopen.cloud:
            sso2.massopen.cloud:
        hil_servers:
          hosts:
            kumo-hil-client.infra.massopen.cloud:
        mirrors:
          hosts:
            mochat.massopen.cloud:
